### ISSUE TITLE
Erro no import de devolução de transferência

### ISSUE THREAD

**Issue by gabrielsntr** [3t1n/NubankPBI#1]
Primeiramente parabéns pelo trabalho. 

Quando eu fui tentar executar o import utilizando meus dados, obtive um erro durante a importação do histórico do débito. O objeto retornado para uma devolução de transferência (t['__typename'] == "TransferOutReversalEvent") não possui atributo a key 'amount', sendo assim tive que fixar o valor 0 para continuar.

Executei um print(t.keys()) para analisar e deixo aqui.
![image](https://user-images.githubusercontent.com/39805286/89463276-b1d8b380-d73c-11ea-8441-f785798b350b.png)

**Comment by 3t1n** [comment]
Isso provavelmente é um issue na biblioteca pynubank, provavelmente nesse arquivo que faz consulta ao graphQL, está faltando esse dado na query, por isso ele trás nulo https://github.com/andreroggeri/pynubank/blob/master/pynubank/queries/account_feed.gql.
Vou ver de conseguir dar um patch nisso, lá na biblioteca 
Se você conseguir abrir esse arquivo localmente na sua máquina, tente adicionar essa linha, a consulta
`... on TransferOutReversalEvent{
                    amount
                }`

**Comment by 3t1n** [comment]
O único problema que eu não tenho como testar essa movimentação pois não possuo ela, teria como você fazer essa adição, na consulta e verificar se o amount está vindo com valor?

**Comment by gabrielsntr** [comment]
Acabei de fazer as alterações, testei e rodou.

**Comment by 3t1n** [comment]
Ok, Mandei solicitação de pull request na biblioteca, o autor aceitando o erro já vai ser resolvido para todos, muito obrigado ;)
